install:
  - go install ./cmd/xkb
  - go install ./cmd/xkc
  - go install ./cmd/xkd
  - sh -c "cp $(which xkd) script/xephon-k-cassandra/node"
  # - go install ./pkg/bin/xnaive
  # - go install ./pkg/bin/xbucket
  # - go install ./pkg/bin/xapi
test:
  - go test -short -v -cover ./pkg/...
scripts:
  runc:
    - docker run --name tsdb-cassandra -p 9042:9042 -d cassandra:3.9
  start:
    - docker start tsdb-cassandra
  f:
    - gofmt -d -l -w ./pkg
  d:
    - sh -c "xkd"
  naive:
    # FIXME: it seems to be my Fedora has some very strict network configuration for docker
    - sh -c "xnaive"
  bucket:
    - sh -c "xbucket"
  api:
    - sh -c "xapi"
