language: go
sudo: true
git:
  depth: 3

go:
  - 1.9.x
  - "1.10"
  - tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep version
  - dep ensure
  - pwd

script:
  - make install
  - xk version --verbose
  - xkctl version --verbose
  - make test