# Xephon-K benchmark config example
log:
  level: info
  color: true
  source: false
# local/remote
# TODO: remote is not supported, but we should, and it should also be able to spawn the needed resources
mode: local
loader:
  target: xephonk
  # limitBy: time | points
  limitBy: time
  points: -1
  series: 100
  time: 10
  worker: 100
  workerTimeout: 30
#  TODO: qps is not supported
#  qps: -1
#generator:
#  timeInterval: 1s
#  timeNoise: false
#  int:
#    max: 10
#    min: 1
#  double:
#    max: 1.0
#    min: 2.2
#  batchSize: 100
#  series: 10
#  #  int: 0.1
#  #  double: 0.9
#reporter:
  # report to tsdb
  # aggregation interval etc.
#  interval:
targets:
  influxdb:
    host: localhost
    port: 8086
    url: write?db=sb
  xephonk:
    host: localhost
    port: 2333
    url: write
  kairosdb:
    host: localhost
    port: 8080
    url: api/v1/datapoints

