# Xephon-K Daemon config example
# NOTE: logging block is same in both daemon and bench
log:
  level: info
  color: true
  source: false
  # TODO: wait until filter in gommon is usable
  # filter: k.server.xxx
  # TODO: wait until human package is added to gommon
  # human: true
storage:
  memory:
    # row/column
    layout: row
    # TODO: custom type with custom marshaler and unmarshaler
    # 1 KB 1024 1 MB 1048576
    # 100 MB
    chunkSize: 104857600
    enableIndex: true
  disk:
    folder: /tmp
    concurrentWriteFiles: 1
    # 1 KB 1024 1 MB 1048576
    # 512 MB
    singleFileSize: 536870912
  cassandra:
    host: localhost
    port: 9042
    # TODO: cache, concurrent write etc.
server:
  http:
    host: localhost
    port: 2333
    enabled: true
  grpc:
    host: localhost
    port: 2334
    enabled: false

